// Code generated by "stringer -type=OpCodeVal"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_MOVIR-0]
	_ = x[OP_MOVRR-1]
	_ = x[OP_MOVDR-2]
	_ = x[OP_MOVDRO1-3]
	_ = x[OP_MOVDRO2-4]
	_ = x[OP_MOVID-5]
	_ = x[OP_MOVRD-6]
	_ = x[OP_MOVRDO1-7]
	_ = x[OP_MOVRDO2-8]
	_ = x[OP_MOVIDO1_NO-9]
	_ = x[OP_MOVIDO1-10]
	_ = x[OP_MOVIDO2_NO-11]
	_ = x[OP_MOVIDO2-12]
	_ = x[OP_MOVSXRR-13]
	_ = x[OP_MOVZXRR-14]
	_ = x[OP_MOVZXIR-15]
	_ = x[OP_MOVZXDR-16]
	_ = x[OP_MOVZXDRO1-17]
	_ = x[OP_MOVZXDRO2-18]
	_ = x[OP_ADDRR-19]
	_ = x[OP_ADDIR-20]
	_ = x[OP_SUBRR-21]
	_ = x[OP_SUBIR-22]
	_ = x[OP_MULRR-23]
	_ = x[OP_DIVRR-24]
	_ = x[OP_NOT-25]
	_ = x[OP_ANDRR-26]
	_ = x[OP_ANDIR-27]
	_ = x[OP_ORRR-28]
	_ = x[OP_ORIR-29]
	_ = x[OP_XORRR-30]
	_ = x[OP_XORIR-31]
	_ = x[OP_LSHRR-32]
	_ = x[OP_LSHIR-33]
	_ = x[OP_RSHRR-34]
	_ = x[OP_RSHIR-35]
	_ = x[OP_INCR-36]
	_ = x[OP_DECR-37]
	_ = x[OP_PUSHR-38]
	_ = x[OP_PUSHI-39]
	_ = x[OP_POP-40]
	_ = x[OP_JMP-41]
	_ = x[OP_JMPE-42]
	_ = x[OP_JMPZ-43]
	_ = x[OP_JMPNE-44]
	_ = x[OP_JMPNZ-45]
	_ = x[OP_JMPG-46]
	_ = x[OP_JMPGE-47]
	_ = x[OP_JMPL-48]
	_ = x[OP_JMPLE-49]
	_ = x[OP_JMPS-50]
	_ = x[OP_JMPNS-51]
	_ = x[OP_JMPC-52]
	_ = x[OP_JMPNC-53]
	_ = x[OP_JMPO-54]
	_ = x[OP_JMPNO-55]
	_ = x[OP_JMPIP-56]
	_ = x[OP_JMPEIP-57]
	_ = x[OP_JMPZIP-58]
	_ = x[OP_JMPNEIP-59]
	_ = x[OP_JMPNZIP-60]
	_ = x[OP_JMPGIP-61]
	_ = x[OP_JMPGEIP-62]
	_ = x[OP_JMPLIP-63]
	_ = x[OP_JMPLEIP-64]
	_ = x[OP_JMPSIP-65]
	_ = x[OP_JMPNSIP-66]
	_ = x[OP_JMPCIP-67]
	_ = x[OP_JMPNCIP-68]
	_ = x[OP_JMPOIP-69]
	_ = x[OP_JMPNOIP-70]
	_ = x[OP_CMPRR-71]
	_ = x[OP_CMPIR-72]
	_ = x[OP_CLR-73]
	_ = x[OP_CALL-74]
	_ = x[OP_CALLIP-75]
	_ = x[OP_RET-76]
	_ = x[OP_EXITI-77]
	_ = x[OP_EXITR-78]
	_ = x[OP_NOP-79]
}

const _OpCodeVal_name = "OP_MOVIROP_MOVRROP_MOVDROP_MOVDRO1OP_MOVDRO2OP_MOVIDOP_MOVRDOP_MOVRDO1OP_MOVRDO2OP_MOVIDO1_NOOP_MOVIDO1OP_MOVIDO2_NOOP_MOVIDO2OP_MOVSXRROP_MOVZXRROP_MOVZXIROP_MOVZXDROP_MOVZXDRO1OP_MOVZXDRO2OP_ADDRROP_ADDIROP_SUBRROP_SUBIROP_MULRROP_DIVRROP_NOTOP_ANDRROP_ANDIROP_ORRROP_ORIROP_XORRROP_XORIROP_LSHRROP_LSHIROP_RSHRROP_RSHIROP_INCROP_DECROP_PUSHROP_PUSHIOP_POPOP_JMPOP_JMPEOP_JMPZOP_JMPNEOP_JMPNZOP_JMPGOP_JMPGEOP_JMPLOP_JMPLEOP_JMPSOP_JMPNSOP_JMPCOP_JMPNCOP_JMPOOP_JMPNOOP_JMPIPOP_JMPEIPOP_JMPZIPOP_JMPNEIPOP_JMPNZIPOP_JMPGIPOP_JMPGEIPOP_JMPLIPOP_JMPLEIPOP_JMPSIPOP_JMPNSIPOP_JMPCIPOP_JMPNCIPOP_JMPOIPOP_JMPNOIPOP_CMPRROP_CMPIROP_CLROP_CALLOP_CALLIPOP_RETOP_EXITIOP_EXITROP_NOP"

var _OpCodeVal_index = [...]uint16{0, 8, 16, 24, 34, 44, 52, 60, 70, 80, 93, 103, 116, 126, 136, 146, 156, 166, 178, 190, 198, 206, 214, 222, 230, 238, 244, 252, 260, 267, 274, 282, 290, 298, 306, 314, 322, 329, 336, 344, 352, 358, 364, 371, 378, 386, 394, 401, 409, 416, 424, 431, 439, 446, 454, 461, 469, 477, 486, 495, 505, 515, 524, 534, 543, 553, 562, 572, 581, 591, 600, 610, 618, 626, 632, 639, 648, 654, 662, 670, 676}

func (i OpCodeVal) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCodeVal_index)-1 {
		return "OpCodeVal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCodeVal_name[_OpCodeVal_index[idx]:_OpCodeVal_index[idx+1]]
}
