// Code generated by "stringer -type=OpCodeVal"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_MOVIR-0]
	_ = x[OP_MOVRR-1]
	_ = x[OP_MOVDRI-2]
	_ = x[OP_MOVDRO1-3]
	_ = x[OP_MOVDRO2-4]
	_ = x[OP_MOVID-5]
	_ = x[OP_MOVRD-6]
	_ = x[OP_MOVRDO1-7]
	_ = x[OP_MOVRDO2-8]
	_ = x[OP_MOVIDO1_NO-9]
	_ = x[OP_MOVIDO1-10]
	_ = x[OP_MOVIDO2_NO-11]
	_ = x[OP_MOVIDO2-12]
	_ = x[OP_ADDRR-13]
	_ = x[OP_ADDIR-14]
	_ = x[OP_SUBRR-15]
	_ = x[OP_SUBIR-16]
	_ = x[OP_MULRR-17]
	_ = x[OP_DIVRR-18]
	_ = x[OP_NOT-19]
	_ = x[OP_ANDRR-20]
	_ = x[OP_ANDIR-21]
	_ = x[OP_ORRR-22]
	_ = x[OP_ORIR-23]
	_ = x[OP_XORRR-24]
	_ = x[OP_XORIR-25]
	_ = x[OP_LSHRR-26]
	_ = x[OP_LSHIR-27]
	_ = x[OP_RSHRR-28]
	_ = x[OP_RSHIR-29]
	_ = x[OP_INCR-30]
	_ = x[OP_DECR-31]
	_ = x[OP_PUSHR-32]
	_ = x[OP_PUSHI-33]
	_ = x[OP_POP-34]
	_ = x[OP_JMP-35]
	_ = x[OP_JMPE-36]
	_ = x[OP_JMPZ-37]
	_ = x[OP_JMPNE-38]
	_ = x[OP_JMPNZ-39]
	_ = x[OP_JMPG-40]
	_ = x[OP_JMPGE-41]
	_ = x[OP_JMPL-42]
	_ = x[OP_JMPLE-43]
	_ = x[OP_JMPS-44]
	_ = x[OP_JMPNS-45]
	_ = x[OP_JMPC-46]
	_ = x[OP_JMPNC-47]
	_ = x[OP_JMPO-48]
	_ = x[OP_JMPNO-49]
	_ = x[OP_JMPIP-50]
	_ = x[OP_JMPEIP-51]
	_ = x[OP_JMPZIP-52]
	_ = x[OP_JMPNEIP-53]
	_ = x[OP_JMPNZIP-54]
	_ = x[OP_JMPGIP-55]
	_ = x[OP_JMPGEIP-56]
	_ = x[OP_JMPLIP-57]
	_ = x[OP_JMPLEIP-58]
	_ = x[OP_JMPSIP-59]
	_ = x[OP_JMPNSIP-60]
	_ = x[OP_JMPCIP-61]
	_ = x[OP_JMPNCIP-62]
	_ = x[OP_JMPOIP-63]
	_ = x[OP_JMPNOIP-64]
	_ = x[OP_CMPRR-65]
	_ = x[OP_CMPIR-66]
	_ = x[OP_CLR-67]
	_ = x[OP_CALL-68]
	_ = x[OP_CALLIP-69]
	_ = x[OP_RET-70]
	_ = x[OP_EXITI-71]
	_ = x[OP_EXITR-72]
	_ = x[OP_NOP-73]
}

const _OpCodeVal_name = "OP_MOVIROP_MOVRROP_MOVDRIOP_MOVDRO1OP_MOVDRO2OP_MOVIDOP_MOVRDOP_MOVRDO1OP_MOVRDO2OP_MOVIDO1_NOOP_MOVIDO1OP_MOVIDO2_NOOP_MOVIDO2OP_ADDRROP_ADDIROP_SUBRROP_SUBIROP_MULRROP_DIVRROP_NOTOP_ANDRROP_ANDIROP_ORRROP_ORIROP_XORRROP_XORIROP_LSHRROP_LSHIROP_RSHRROP_RSHIROP_INCROP_DECROP_PUSHROP_PUSHIOP_POPOP_JMPOP_JMPEOP_JMPZOP_JMPNEOP_JMPNZOP_JMPGOP_JMPGEOP_JMPLOP_JMPLEOP_JMPSOP_JMPNSOP_JMPCOP_JMPNCOP_JMPOOP_JMPNOOP_JMPIPOP_JMPEIPOP_JMPZIPOP_JMPNEIPOP_JMPNZIPOP_JMPGIPOP_JMPGEIPOP_JMPLIPOP_JMPLEIPOP_JMPSIPOP_JMPNSIPOP_JMPCIPOP_JMPNCIPOP_JMPOIPOP_JMPNOIPOP_CMPRROP_CMPIROP_CLROP_CALLOP_CALLIPOP_RETOP_EXITIOP_EXITROP_NOP"

var _OpCodeVal_index = [...]uint16{0, 8, 16, 25, 35, 45, 53, 61, 71, 81, 94, 104, 117, 127, 135, 143, 151, 159, 167, 175, 181, 189, 197, 204, 211, 219, 227, 235, 243, 251, 259, 266, 273, 281, 289, 295, 301, 308, 315, 323, 331, 338, 346, 353, 361, 368, 376, 383, 391, 398, 406, 414, 423, 432, 442, 452, 461, 471, 480, 490, 499, 509, 518, 528, 537, 547, 555, 563, 569, 576, 585, 591, 599, 607, 613}

func (i OpCodeVal) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCodeVal_index)-1 {
		return "OpCodeVal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCodeVal_name[_OpCodeVal_index[idx]:_OpCodeVal_index[idx+1]]
}
