# Each instruction is comprised of an opcode section and a parameter section
# The opcode section is 4 bytes and the parameter section is 8 bytes
# Those sizes are fixed, every instruction is the same size
# Some instructions store parameter information in the opcode section
# For example the MOVIR instruction puts in the last byte of its opcode
# the destination register and its size.
# This is important when it comes to decoding the instructions since
# parts of the opcode are variable and can be different yet still map to the same
# instruction. An opcode for MOVIR with destination register r0 will look different
# then the same instruction where the destination register is r1. The first 3 bytes will
# be the same for both but the last byte will be different. The decoder is aware of this
# and will disregard that last byte which will be analyzed by the virtual machine instead.

# defines an instruction in the instruction set
[op.MOVIR]
# describes the instruction
desc = "Move immediate value into a register"
# describes how many bytes in the opcode are reserved for parameters to the instruction
reserve.size = 1
# describes the function of each bit in the reserved bytes
# from right to left, since the system is big endian
[[op.MOVIR.reserve.doc]]
# bits 0-3
bits = 4
desc = "Destination register"
[[op.MOVIR.reserve.doc]]
# bits 4-5
bits = 2
desc = "Unused"
[[op.MOVIR.reserve.doc]]
# bits 6-7
bits = 2
desc = "Size of the destination register"
# describes the function of the bits in the parameter section of the instruction
[[op.MOVIR.param]]
bits = 64
desc = "Immediate value, will be truncated to fit destination size"


[op.MOVRR]
desc = "Move a value from one register to another register"
reserve.size = 0
[[op.MOVRR.param]]
bits = 4
desc = "Destination register"
[[op.MOVRR.param]]
bits = 4
desc = "Source register"
[[op.MOVRR.param]]
bits = 2
desc = "Source size"
[[op.MOVRR.param]]
bits = 2
desc = "Destination size"
[[op.MOVRR.param]]
bits = 52
desc = "Unused"

[op.MOVDR]
desc = "Move a value from an address to a register"
reserve.size = 1
[[op.MOVDR.reserve.doc]]
bits = 4
desc = "Destination register"
[[op.MOVDR.reserve.doc]]
bits = 2
desc = "Destination size"
[[op.MOVDR.reserve.doc]]
bits = 2
desc = "Unused"
[[op.MOVDR.param]]
bits = 64
desc = "Immediate address value"

[op.MOVDRO1]
desc = "Move a value from an address to a register with the address being based in a register"
reserve.size = 2
[[op.MOVDRO1.reserve.doc]]
bits = 2
desc = "Type of arthmetic operation between the offset and the register"
[[op.MOVDRO1.reserve.doc]]
bits = 2
desc = "Size of the base register"
[[op.MOVDRO1.reserve.doc]]
bits = 2
desc = "Size of the destination register"
[[op.MOVDRO1.reserve.doc]]
bits = 2
desc = "Scale factor type"
[[op.MOVDRO1.reserve.doc]]
bits = 4
desc = "Base register"
[[op.MOVDRO1.reserve.doc]]
bits = 4
desc = "Destination register"
[[op.MOVDRO1.param]]
bits = 64
desc = "Immediate value offset"

[op.MOVDRO2]
desc = '''
Move a value from an address to a register with the address being derived from
a base register being offset by an index register and immediate value offset
'''
reserve.size = 3
[[op.MOVDRO2.reserve.doc]]
bits = 2
desc = '''
    Destination register size
'''
[[op.MOVDRO2.reserve.doc]]
bits = 2
desc = '''
    Scale factor
'''
[[op.MOVDRO2.reserve.doc]]
bits = 4
desc = '''
    Unused
'''
[[op.MOVDRO2.reserve.doc]]
bits = 2
desc = '''
    Offset operator (addition or subtraction)
'''
[[op.MOVDRO2.reserve.doc]]
bits = 2
desc = '''
    Size of base and index registers (both at once)
'''
[[op.MOVDRO2.reserve.doc]]
bits = 4
desc = '''
    Index register
'''
[[op.MOVDRO2.reserve.doc]]
bits = 4
desc = '''
    Base register
'''
[[op.MOVDRO2.reserve.doc]]
bits = 4
desc = '''
    Destination register
'''
[[op.MOVDRO2.param]]
bits = 64
desc = "Immediate value offset"

[op.MOVID]
desc = '''
Move immediate value into an address
'''
reserve.size = 1
[[op.MOVID.reserve.doc]]
bits = 2
desc = '''Data size'''
[[op.MOVID.reserve.doc]]
bits = 6
desc = '''Unused '''
[[op.MOVID.param]]
bits = 32
desc = "Immediate value, 32-bit signed integer"
[[op.MOVID.param]]
bits = 32
desc = "Address, 32-bit unsigned integer"

[op.MOVRD]
desc = "Move a value from a register into an address"
reserve.size = 1
[[op.MOVRD.reserve.doc]]
bits = 4
desc = '''Source register'''
[[op.MOVRD.reserve.doc]]
bits = 2
desc = '''Source register size'''
[[op.MOVRD.reserve.doc]]
bits = 2
desc = '''Unused'''

[[op.MOVRD.param]]
bits = 64
desc = '''Address as 64-bit immediate value unsigned integer'''

[op.MOVRDO1]
desc = "Move a value from a register into an address with a base register and an offset"
reserve.size = 2

[[op.MOVRDO1.reserve.doc]]
bits = 2
desc = 'Offset operand type'
[[op.MOVRDO1.reserve.doc]]
bits = 2
desc = 'Base register size'
[[op.MOVRDO1.reserve.doc]]
bits = 2
desc = 'Destination register size'
[[op.MOVRDO1.reserve.doc]]
bits = 2
desc = 'Scale factor'
[[op.MOVRDO1.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVRDO1.reserve.doc]]
bits = 4
desc = 'Destination register'

[[op.MOVRDO1.param]]
bits = 64
desc = 'Unsigned 64-bit immediate value offset'

[op.MOVRDO2]
desc = "Move a value from a register into an address with a base register, index register and an offset"
reserve.size = 3

[[op.MOVRDO2.reserve.doc]]
bits = 2
desc = 'Destination register size'
[[op.MOVRDO2.reserve.doc]]
bits = 2
desc = 'Size factor'
[[op.MOVRDO2.reserve.doc]]
bits = 4
desc = 'Unused'
[[op.MOVRDO2.reserve.doc]]
bits = 2
desc = 'Offset operator type'
[[op.MOVRDO2.reserve.doc]]
bits = 2
desc = 'Base and index register size'
[[op.MOVRDO2.reserve.doc]]
bits = 4
desc = 'Index register'
[[op.MOVRDO2.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVRDO2.reserve.doc]]
bits = 4
desc = 'Destination register'

[[op.MOVRDO2.param]]
bits = 64
desc = 'Unsigned 64-bit immediate value offset'

[op.MOVIDO1_NO]
desc = "Move immediate value into an address with a base register and NO offset"
reserve.size = 2

[[op.MOVIDO1_NO.reserve.doc]]
bits = 2
desc = 'Offset operand type'
[[op.MOVIDO1_NO.reserve.doc]]
bits = 2
desc = 'Base register size'
[[op.MOVIDO1_NO.reserve.doc]]
bits = 2
desc = 'Destination address size'
[[op.MOVIDO1_NO.reserve.doc]]
bits = 2
desc = 'Scale factor'
[[op.MOVIDO1_NO.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVIDO1_NO.reserve.doc]]
bits = 4
desc = 'Unused'

[[op.MOVIDO1_NO.param]]
bits = 64
desc = "Unsigned 64-bit integer immediate value"


[op.MOVIDO1]
desc = "Move immediate value into an address with a base register and NO offset"
reserve.size = 2

[[op.MOVIDO1.reserve.doc]]
bits = 2
desc = 'Offset operand type'
[[op.MOVIDO1.reserve.doc]]
bits = 2
desc = 'Base register size'
[[op.MOVIDO1.reserve.doc]]
bits = 2
desc = 'Destination address size'
[[op.MOVIDO1.reserve.doc]]
bits = 2
desc = 'Scale factor'
[[op.MOVIDO1.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVIDO1.reserve.doc]]
bits = 4
desc = 'Unused'

[[op.MOVIDO1.param]]
bits = 32
desc = "Unsigned 32-bit integer immediate value"
[[op.MOVIDO1.param]]
bits = 32
desc = "Signed 32-bit integer immediate value offset"

[op.MOVIDO2_NO]
desc = "Move immediate value into an address with a base register, index register and NO offset"
reserve.size = 3

[[op.MOVIDO2_NO.reserve.doc]]
bits = 2
desc = 'Unused'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 2
desc = 'Size factor'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 4
desc = 'Unused'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 2
desc = 'Offset operator type'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 2
desc = 'Base and index register size'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 4
desc = 'Index register'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVIDO2_NO.reserve.doc]]
bits = 4
desc = 'Destination register'

[[op.MOVIDO2_NO.param]]
bits = 64
desc = '64-bit immediate value'


[op.MOVIDO2]
desc = "Move immediate value into an address with a base register, index register and NO offset"
reserve.size = 3

[[op.MOVIDO2.reserve.doc]]
bits = 2
desc = 'Unused'
[[op.MOVIDO2.reserve.doc]]
bits = 2
desc = 'Size factor'
[[op.MOVIDO2.reserve.doc]]
bits = 4
desc = 'Unused'
[[op.MOVIDO2.reserve.doc]]
bits = 2
desc = 'Offset operator type'
[[op.MOVIDO2.reserve.doc]]
bits = 2
desc = 'Base and index register size'
[[op.MOVIDO2.reserve.doc]]
bits = 4
desc = 'Index register'
[[op.MOVIDO2.reserve.doc]]
bits = 4
desc = 'Base register'
[[op.MOVIDO2.reserve.doc]]
bits = 4
desc = 'Destination register'

[[op.MOVIDO2.param]]
bits = 32
desc = '32-bit immediate value'
[[op.MOVIDO2.param]]
bits = 32
desc = 'Signed 32-bit immediate value'

[op.MOVSXRR]
desc = "Move a value from one register to another register with sign extension"
reserve.size = 0
[[op.MOVSXRR.param]]
bits = 4
desc = "Destination register"
[[op.MOVSXRR.param]]
bits = 4
desc = "Source register"
[[op.MOVSXRR.param]]
bits = 2
desc = "Source size"
[[op.MOVSXRR.param]]
bits = 2
desc = "Destination size"
[[op.MOVSXRR.param]]
bits = 52
desc = "Unused"

[op.MOVZXRR]
desc = "Move a value from one register to another register with zero extension"
reserve.size = 0
[[op.MOVZXRR.param]]
bits = 4
desc = "Destination register"
[[op.MOVZXRR.param]]
bits = 4
desc = "Source register"
[[op.MOVZXRR.param]]
bits = 2
desc = "Source size"
[[op.MOVZXRR.param]]
bits = 2
desc = "Destination size"
[[op.MOVZXRR.param]]
bits = 52
desc = "Unused"

[op.MOVZXIR]
desc = "Move immediate value into a register with zero extension"
reserve.size = 1
[[op.MOVZXIR.reserve.doc]]
bits = 4
desc = "Destination register"
[[op.MOVZXIR.reserve.doc]]
bits = 2
desc = "Unused"
[[op.MOVZXIR.reserve.doc]]
bits = 2
desc = "Size of the destination register"
[[op.MOVZXIR.param]]
bits = 64
desc = "Immediate value"

[op.MOVZXDR]
desc = "Move a value from an address to a register with zero extension"
reserve.size = 1
[[op.MOVZXDR.reserve.doc]]
bits = 4
desc = "Destination register"
[[op.MOVZXDR.reserve.doc]]
bits = 2
desc = "Destination size"
[[op.MOVZXDR.reserve.doc]]
bits = 2
desc = "Unused"
[[op.MOVZXDR.param]]
bits = 64
desc = "Immediate address value"

[op.MOVZXDRO1]
desc = "Move a value from an address to a register with the address being based in a register with zero extension"
reserve.size = 2
[[op.MOVZXDRO1.reserve.doc]]
bits = 2
desc = "Type of arthmetic operation between the offset and the register"
[[op.MOVZXDRO1.reserve.doc]]
bits = 2
desc = "Size of the base register"
[[op.MOVZXDRO1.reserve.doc]]
bits = 2
desc = "Size of the destination register"
[[op.MOVZXDRO1.reserve.doc]]
bits = 2
desc = "Scale factor type"
[[op.MOVZXDRO1.reserve.doc]]
bits = 4
desc = "Base register"
[[op.MOVZXDRO1.reserve.doc]]
bits = 4
desc = "Destination register"
[[op.MOVZXDRO1.param]]
bits = 64
desc = "Immediate value offset"

[op.MOVZXDRO2]
desc = '''
Move a value from an address to a register with the address being derived from
a base register being offset by an index register and immediate value offset with zero extension
'''
reserve.size = 3
[[op.MOVZXDRO2.reserve.doc]]
bits = 2
desc = '''
    Destination register size
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 2
desc = '''
    Scale factor
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 4
desc = '''
    Unused
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 2
desc = '''
    Offset operator (addition or subtraction)
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 2
desc = '''
    Size of base and index registers (both at once)
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 4
desc = '''
    Index register
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 4
desc = '''
    Base register
'''
[[op.MOVZXDRO2.reserve.doc]]
bits = 4
desc = '''
    Destination register
'''
[[op.MOVZXDRO2.param]]
bits = 64
desc = "Immediate value offset"

[op.MOVSB]
desc = "Move single byte from r5 to r6"
reserve.size = 0
[[op.MOVSB.param]]
bits = 64
desc = 'Unused'

[op.MOVREPSB]
desc = "Move single byte from r5 to r6, decrement r7 until it becomes zero and then stop. If the DF flag is set then decrement r5 and r6 if not then increment r5 and r6."
reserve.size = 0
[[op.MOVREPSB.param]]
bits = 64
desc = 'Unused'


# [op.MOVSQ]
# [op.MOVREPSQ]
# [op.MOVSH]
# [op.MOVREPSH]
# [op.MOVSW]
# [op.MOVREPSW]
# [op.XCHGRR]
# [op.XCHGDR]
# [op.XCHGDRO1]
# [op.XCHGDRO2]
# [op.LEADRO1]
# [op.LEADRO2]
# [op.ADDRR]
# [op.ADDIR]
# [op.SUBRR]
# [op.SUBIR]
# [op.MULRR]
# [op.DIVRR]
# [op.NOT]
# [op.NEG]
# [op.ROL]
# [op.ROR]
# [op.ANDRR]
# [op.ANDIR]
# [op.ORRR]
# [op.ORIR]
# [op.XORRR]
# [op.XORIR]
# [op.LSHRR]
# [op.LSHIR]
# [op.RSHRR]
# [op.RSHIR]
# [op.INCR]
# [op.DECR]
# [op.PUSHR]
# [op.PUSHI]
# [op.POP]
# [op.JMP]
# [op.JMPE]
# [op.JMPZ]
# [op.JMPNE]
# [op.JMPNZ]
# [op.JMPG]
# [op.JMPGE]
# [op.JMPL]
# [op.JMPLE]
# [op.JMPS]
# [op.JMPNS]
# [op.JMPC]
# [op.JMPNC]
# [op.JMPO]
# [op.JMPNO]
# [op.JMPIP]
# [op.JMPEIP]
# [op.JMPZIP]
# [op.JMPNEIP]
# [op.JMPNZIP]
# [op.JMPGIP]
# [op.JMPGEIP]
# [op.JMPLIP]
# [op.JMPLEIP]
# [op.JMPSIP]
# [op.JMPNSIP]
# [op.JMPCIP]
# [op.JMPNCIP]
# [op.JMPOIP]
# [op.JMPNOIP]
# [op.CMPRR]
# [op.CMPIR]
# [op.CLR]
# [op.CALL]
# [op.CALLIP]
# [op.RET]
# [op.EXITI]
# [op.EXITR]
# [op.SDF]
# [op.CDF]
# [op.NOP]
