// Code generated by "stringer -type=JmpVariant"; DO NOT EDIT.

package assembler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JMP-0]
	_ = x[JMPE-1]
	_ = x[JMPZ-2]
	_ = x[JMPNE-3]
	_ = x[JMPNZ-4]
	_ = x[JMPG-5]
	_ = x[JMPGE-6]
	_ = x[JMPL-7]
	_ = x[JMPLE-8]
	_ = x[JMPS-9]
	_ = x[JMPNS-10]
	_ = x[JMPC-11]
	_ = x[JMPNC-12]
	_ = x[JMPO-13]
	_ = x[JMPNO-14]
	_ = x[JMPIP0R-15]
	_ = x[JMPIP1R-16]
}

const _JmpVariant_name = "JMPJMPEJMPZJMPNEJMPNZJMPGJMPGEJMPLJMPLEJMPSJMPNSJMPCJMPNCJMPOJMPNOJMPIP0RJMPIP1R"

var _JmpVariant_index = [...]uint8{0, 3, 7, 11, 16, 21, 25, 30, 34, 39, 43, 48, 52, 57, 61, 66, 73, 80}

func (i JmpVariant) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_JmpVariant_index)-1 {
		return "JmpVariant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JmpVariant_name[_JmpVariant_index[idx]:_JmpVariant_index[idx+1]]
}
