// Code generated by "stringer -type=LogTy"; DO NOT EDIT.

package assembler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AND-0]
	_ = x[OR-1]
	_ = x[XOR-2]
	_ = x[LSH-3]
	_ = x[RSH-4]
}

const _LogTy_name = "ANDORXORLSHRSH"

var _LogTy_index = [...]uint8{0, 3, 5, 8, 11, 14}

func (i LogTy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LogTy_index)-1 {
		return "LogTy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogTy_name[_LogTy_index[idx]:_LogTy_index[idx+1]]
}
