package errors

const (
	ERR_DISALLOWED_SOURCE_REGISTER = iota
	ERR_DISALLOWED_DESTINATION_REGISTER
	ERR_DISALLOWED_OPERAND_1_REGISTER
	ERR_DISALLOWED_OPERAND_2_REGISTER
	ERR_BAD_OPCODE
	ERR_STACK_UNDERFLOW
)

