// Code generated by "stringer -type=ArthTy"; DO NOT EDIT.

package assembler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADD-0]
	_ = x[SUB-1]
	_ = x[DIV-2]
	_ = x[MUL-3]
}

const _ArthTy_name = "ADDSUBDIVMUL"

var _ArthTy_index = [...]uint8{0, 3, 6, 9, 12}

func (i ArthTy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArthTy_index)-1 {
		return "ArthTy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArthTy_name[_ArthTy_index[idx]:_ArthTy_index[idx+1]]
}
