package main

import (
	"encoding/binary"
	"fmt"
	"maps"
	"math/rand"
	"os"
	"slices"
	"strings"
	"unicode"

	"github.com/JakubCygaro/alphataurus/internal/pkg/opt"
	toml "github.com/pelletier/go-toml/v2"

	arg "github.com/alexflint/go-arg"
)

var args struct {
	InputFile   string `arg:"positional,required" help:"Input instruction specification .toml file path"`
	PackageName string `arg:"-p,--package,required" help:"Name of the package the output file should belong to"`
	OutputFile  string `arg:"-o,--output" help:"Path and name of the output file, .go will be appended to it"`
	Print       bool   `arg:"--print," help:"Print out the generated output file to stdout"`
	WriteTest   bool   `arg:"-t,--test," help:"Write a test file along with the output file with _test appended to the name"`
	Stringer    bool   `arg:"--stringer" help:"Add a go:generate comment to output that uses stringer to implement String() for OpCodeVal"`
}

func exitWithErr(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format, a...)
	os.Exit(1)
}

type Spec struct {
	// Instruction opcode name
	Name string
	// Instruction description
	Desc string
	// What bytes from the opcode portion of the instruction
	// are reserved as parameters to the instruction
	Reserve struct {
		// Byte count
		Size int
		// Bit documentation, the system is big endian so it goes from
		// right to left
		Doc []struct {
			Bits int
			Desc string
		}
	}
	// What bits of the argument portion of the instruction mean
	Param []struct {
		// Bit documentation, the system is big endian so it goes from
		// right to left
		Bits int
		Desc string
	}
}
type OpSpec struct {
	// Opcodes defined
	Op []Spec
}

func main() {
	if err := arg.Parse(&args); err != nil {
		exitWithErr("%s\n", err.Error())
	}
	var read []byte
	if f, err := os.ReadFile(args.InputFile); err != nil {
		exitWithErr("%s\n", err.Error())
	} else {
		read = f
	}
	var spec OpSpec
	if err := toml.Unmarshal(read, &spec); err != nil {
		exitWithErr("%s\n", err.Error())
	}
	built, test, err := buildSourceAndTest(spec, args.WriteTest, args.Stringer)
	if err != nil {
		exitWithErr("%s\n", err.Error())
	}
	template :=
		`
// This file was automatically generated by makedec utility

package %s

%s
	`
	if args.Print {
		fmt.Fprintf(
			os.Stdout,
			template,
			args.PackageName,
			built,
		)
	}
	if args.OutputFile == "" {
		return
	}
	if f, err := os.Create(args.OutputFile + ".go"); err != nil {
		exitWithErr("%s\n", err.Error())
	} else {
		defer f.Close()
		fmt.Fprintf(
			f,
			template,
			args.PackageName,
			built,
		)
	}
	if args.WriteTest {
		if f, err := os.Create(args.OutputFile + "_test.go"); err != nil {
			exitWithErr("%s\n", err.Error())
		} else {
			defer f.Close()
			fmt.Fprintf(
				f,
				template,
				args.PackageName,
				test,
			)
		}
	}
}

func verifyOpSpec(spec *Spec) error {
	if strings.ContainsFunc(spec.Name, func(r rune) bool {
		return unicode.IsSpace(r) ||
			(unicode.IsPunct(r) && r != '_') ||
			unicode.IsControl(r)
	}) {
		return fmt.Errorf(
			"Spec for opcode `%s` contains disallowed characters.",
			spec.Name,
		)
	}
	if spec.Desc == "" {
		return fmt.Errorf(
			"Spec for opcode `%s` provides no description, "+
				"please provide a description for this opcode.",
			spec.Name,
		)
	}
	if spec.Reserve.Size < 0 || spec.Reserve.Size > 3 {
		return fmt.Errorf(
			"Spec for opcode `%s` reserves a disallowed amount of bytes (%d).",
			spec.Name,
			spec.Reserve.Size,
		)
	}
	reserved := spec.Reserve.Size * 8
	for i, bitDoc := range spec.Reserve.Doc {
		reserved -= bitDoc.Bits
		if reserved < 0 {
			return fmt.Errorf(
				"Bit doc %d `%s` for opcode `%s` uses "+
					"more bits than are reserved in the spec (%d). "+
					"%d bits over the reserved %d.",
				i,
				bitDoc.Desc,
				spec.Name,
				spec.Reserve.Size,
				-reserved,
				spec.Reserve.Size*8,
			)
		}
		if bitDoc.Desc == "" {
			return fmt.Errorf(
				"Bit doc %d for opcode `%s` provides no usage description (desc). "+
					"Please provide a usage description for these bits.",
				i,
				spec.Name,
			)
		}
	}
	if reserved > 0 {
		return fmt.Errorf(
			"Spec for opcode `%s` does not document all reserved bits."+
				" %d undocumented bits remain.",
			spec.Name,
			reserved,
		)
	}
	paramReserved := 64
	for i, paramDoc := range spec.Param {
		paramReserved -= paramDoc.Bits
		if paramReserved < 0 {
			return fmt.Errorf(
				"Param doc %d `%s` for opcode `%s` uses "+
					"more bits than are allowed for an instruction parameter (64). "+
					"%d bits over the maximum.",
				i,
				paramDoc.Desc,
				spec.Name,
				-paramReserved,
			)
		}
		if paramDoc.Desc == "" {
			return fmt.Errorf(
				"Param doc %d for opcode `%s` provides no usage description (desc). "+
					"Please provide a description for these bits.",
				i,
				spec.Name,
			)
		}
	}
	if paramReserved > 0 {
		return fmt.Errorf(
			"Spec for opcode `%s` does not document all parameter bits."+
				" %d undocumented bits remain.",
			spec.Name,
			paramReserved,
		)
	}
	return nil
}

type OpcodeVal struct {
	Prefix int
	Spec   Spec
}

const OPCODE_MAP_MAX_LAYER = 256

type OpcodeMap struct {
	Prefix       uint8
	Prev         *OpcodeMap
	Layer        [OPCODE_MAP_MAX_LAYER]opt.Either[*OpcodeMap, OpcodeVal]
	next         int
	depth        int
	LastNewLayer *OpcodeMap
}

func (om *OpcodeMap) HasSpace() bool {
	return om.next < OPCODE_MAP_MAX_LAYER
}

func (om *OpcodeMap) PushLayer(layer *OpcodeMap) error {
	if om.depth < 0 {
		return fmt.
			Errorf("Maximum map depth reached")
	}
	if om.next >= OPCODE_MAP_MAX_LAYER {
		return fmt.
			Errorf("Maximum layer size reached")
	}
	om.Layer[om.next] =
		opt.MakeLeft[*OpcodeMap, OpcodeVal](layer)
	om.next++
	om.LastNewLayer = layer
	layer.depth = om.depth - 1
	layer.Prefix = uint8(om.next - 1)
	layer.Prev = om
	return nil
}
func (om *OpcodeMap) PushSpec(s Spec) error {
	if om.next >= OPCODE_MAP_MAX_LAYER {
		return fmt.
			Errorf("Maximum layer size reached with `%s`", s.Name)
	}
	om.Layer[om.next] =
		opt.MakeRight[*OpcodeMap](OpcodeVal{om.next, s})
	om.next++
	return nil
}

var m = OpcodeMap{
	depth: 3,
}

type LayerList []*OpcodeMap

var layers = []LayerList{
	make(LayerList, 0),
	make(LayerList, 0),
	make(LayerList, 0),
	make(LayerList, 0),
}

func insertIntoMap(m *OpcodeMap, spec Spec) error {
	if m.depth > spec.Reserve.Size {
		if m.LastNewLayer != nil &&
			m.LastNewLayer.HasSpace() {
			return insertIntoMap(m.LastNewLayer, spec)
		}
		// backtrack case
		if !m.HasSpace() {
			if m.depth == 3 {
				return fmt.
					Errorf("Instruction opcode space exhausted with `%s`", spec.Name)
			}
			m.Prev.LastNewLayer = nil
			return insertIntoMap(m.Prev, spec)
		}
		lay := &OpcodeMap{}
		if err := m.PushLayer(lay); err != nil {
			return err
		} else {
			layers[lay.depth] = append(layers[lay.depth], lay)
			return insertIntoMap(m.LastNewLayer, spec)
		}
	} else if m.depth == spec.Reserve.Size {
		return m.PushSpec(spec)
	}
	return nil
}

var assignedOpcodes = map[uint32]OpcodeVal{}

func recurseUp(layer *OpcodeMap, bytes []byte) {
	if layer.Prev != nil {
		bytes[layer.depth+1] = layer.Prefix
		recurseUp(layer.Prev, bytes)
	}
}

func assignLayer(ll LayerList) {
	for _, layer := range ll {
		for i := range layer.next {
			if layer.Layer[i].HasLeft() {
				continue
			}
			val := layer.Layer[i].GetRight()
			b := [4]byte{}
			b[layer.depth] = byte(val.Prefix)
			recurseUp(layer, b[:])
			code := binary.BigEndian.Uint32(b[:])
			assignedOpcodes[code] = val
		}
	}
}
func writeOpcodeVals(sb *strings.Builder, code uint32, s OpcodeVal) {
	maxWidth := 25
	opV := fmt.Sprintf("OP_%s_VAL", s.Spec.Name)
	pad := maxWidth - len(opV)
	fmt.Fprintf(
		sb,
		"    %s %*suint32 = 0x%08x\n",
		opV,
		pad,
		"",
		code,
	)
}
func writeOpcodeDecls(sb *strings.Builder, s OpcodeVal) {
	fmt.Fprintf(
		sb,
		"    // Description:\n",
	)
	for l := range strings.Lines(s.Spec.Desc) {
		fmt.Fprintf(
			sb,
			"    // %s\n",
			strings.Trim(l, "\r\n "),
		)
	}
	fmt.Fprintf(
		sb,
		"    //\n",
	)
	if len(s.Spec.Reserve.Doc) > 0 {
		fmt.Fprintf(
			sb,
			"    // Reserved bits:\n    //\n",
		)

	}
	rangeStart := 0
	for _, bit := range s.Spec.Reserve.Doc {
		fmt.Fprintf(
			sb,
			"    // %d-%d\n",
			rangeStart,
			rangeStart+bit.Bits-1,
		)
		for l := range strings.Lines(bit.Desc) {
			fmt.Fprintf(
				sb,
				"    // %s\n"+
					"    //\n",
				strings.Trim(l, "\r\n "),
			)
		}
		rangeStart += bit.Bits
	}
	fmt.Fprintf(
		sb,
		"    // Parameter bits:\n",
	)
	rangeStart = 0
	for _, bit := range s.Spec.Param {
		fmt.Fprintf(
			sb,
			"    // %d-%d\n"+
				"    //\n",
			rangeStart,
			rangeStart+bit.Bits-1,
		)
		for l := range strings.Lines(bit.Desc) {
			fmt.Fprintf(
				sb,
				"    // %s\n",
				strings.Trim(l, "\r\n "),
			)
		}
		rangeStart += bit.Bits
	}
	fmt.Fprintf(
		sb,
		"    OP_%s OpCodeVal = iota\n",
		s.Spec.Name,
	)
}

func writeOpcodeMap(sb *strings.Builder, code uint32, s OpcodeVal) {
	fmt.Fprintf(
		sb,
		"    0x%08x : OP_%s,\n",
		code,
		s.Spec.Name,
	)
}

func writeOpcodeDecodeFunc(sb *strings.Builder) {
	def :=
		`
func Decode(code uint32) (bool, OpCodeVal) {
	if o, ok := _makedec_opcodeMap[code]; ok {
		return ok, o
	}
	if o, ok := _makedec_opcodeMap[(code & 0x00ffffff)]; ok {
		return ok, o
	}
	if o, ok := _makedec_opcodeMap[(code & 0x0000ffff)]; ok {
		return ok, o
	}
	if o, ok := _makedec_opcodeMap[(code & 0x000000ff)]; ok {
		return ok, o
	}
	return false, OpCodeVal(0)
}
`
	fmt.Fprintf(
		sb,
		"%s",
		def,
	)
}

func buildSourceAndTest(
	spec OpSpec,
	buildTest bool,
	stringer bool,
) (src string, tst string, err error) {
	source := strings.Builder{}
	test := strings.Builder{}
	layers[3] = append(layers[3], &m)
	checkMap := make(map[string]struct{})
	// type pair struct {
	// 	Opcode string
	// 	Spec   Spec
	// }
	// sortedSpecs := make([]pair, 0)
	// for _, code := range slices.Sorted(maps.Keys(spec.Op)) {
	// 	sortedSpecs = append(sortedSpecs, pair{
	// 		Opcode: code,
	// 		Spec:   spec.Op[code],
	// 	})
	// }
	for _, s := range spec.Op {
		opcode := s.Name
		if _, used := checkMap[opcode]; used {
			return "", "", fmt.Errorf(
				"'%s' opcode duplication",
				opcode,
			)
		} else {
			checkMap[opcode] = struct{}{}
		}
		spec := s
		if err := verifyOpSpec(&spec); err != nil {
			return "", "", err
		}
		if err := insertIntoMap(&m, spec); err != nil {
			return "", "", err
		}
	}
	for _, ll := range layers {
		assignLayer(ll)
	}
	if stringer {
		source.WriteString("//go:")
		source.WriteString("generate stringer -type=OpCodeVal\n")
	}
	source.WriteString(
		"type OpCodeVal uint32\n" +
			"const (\n",
	)
	if len(assignedOpcodes) != len(spec.Op) {
		return "", "", fmt.Errorf(
			"Failed to assign all opcodes, input does not match output " +
				"(this should not happen)",
		)
	}
	for _, code := range slices.Sorted(maps.Keys(assignedOpcodes)) {
		writeOpcodeDecls(&source, assignedOpcodes[code])
	}
	source.WriteString(
		")\n",
	)
	source.WriteString(
		"var _makedec_opcodeMap = map[uint32]OpCodeVal {\n",
	)
	for _, code := range slices.Sorted(maps.Keys(assignedOpcodes)) {
		writeOpcodeMap(&source, code, assignedOpcodes[code])
	}
	source.WriteString(
		"}\n",
	)
	writeOpcodeDecodeFunc(&source)
	source.WriteString(
		"const (\n",
	)
	for _, code := range slices.Sorted(maps.Keys(assignedOpcodes)) {
		writeOpcodeVals(&source, code, assignedOpcodes[code])
	}
	source.WriteString(
		")\n",
	)
	if buildTest {
		fmt.Fprintf(
			&test,
			`
import ("testing")
func TestDecoder(t* testing.T){
`,
		)
		for _, code := range slices.Sorted(maps.Keys(assignedOpcodes)) {
			writeDecoderTest(&test, code, assignedOpcodes[code])
		}
		fmt.Fprintf(&test, "\n}\n")
	}
	return source.String(), test.String(), nil

}

func writeDecoderTest(sb *strings.Builder, code uint32, op OpcodeVal) {
	noise := uint32(rand.Int31())
	testCode := code
	switch op.Spec.Reserve.Size {
	case 1:
		testCode |= (noise & 0xff000000)
	case 2:
		testCode |= (noise & 0xffff0000)
	case 3:
		testCode |= (noise & 0xffffff00)
	}
	fmt.Fprintf(
		sb,
		`
	if ok, v := Decode(0x%08x); !ok {
		t.Error("Failed to decode opcode OP_%s")
	} else if v != OP_%s {
		t.Errorf("Decoded wrong opcode, wanted OP_%s_VAL, got '0x%%08x'", v)
	}
`,
		testCode,
		op.Spec.Name,
		op.Spec.Name,
		op.Spec.Name,
	)
}
